
- name: 'create artifactory database'
  postgresql_db: name=artdb template='template0' encoding='UTF-8'
  when: features.postgresql

- name: 'create artifactory database user'
  postgresql_user: db=artdb name='{{artifactory_username}}' password='{{artifactory_password}}'
  when: features.postgresql

- name: 'download jdbc connector for postgres'
  get_url: url={{postgres_jdbc_url}} dest={{artifactory_home}}/tomcat/lib
  register: jdbc_installed
  when: features.postgresql

- name: 'verify presence of jdbc connector for mysql'
  stat: path={{artifactory_home}}/tomcat/lib/{{mysql_jdbc_base}}-bin.jar
  register: jdbc_installed
  when: features.mysql

- name: 'download jdbc connector for mysql'
  get_url: url={{mysql_jdbc_url}} dest=/tmp
  when: features.mysql
  retries: 3
#  when: features.mysql and not ant_installed.stat.exists

- name: 'untar jdbc connector for mysql'
  command: tar xfvz /tmp/{{mysql_jdbc_base}}.tar.gz -C /tmp
  when: features.mysql

- name: 'enable  jdbc connector for mysql'
  command: mv /tmp/{{mysql_jdbc_base}}/{{mysql_jdbc_base}}-bin.jar {{artifactory_home}}/tomcat/lib
  when: features.mysql

- name: 'seboolean allow_user_mysql_connect'
  seboolean: name=allow_user_mysql_connect state=yes persistent=yes
  when: features.mysql

- name: 'create artifactory database'
  mysql_db: name=artdb state=present
  when: features.mysql

- name: 'create artifactory database user'
  mysql_user: name={{ artifactory_username }} priv=artdb.*:ALL
    password={{ artifactory_password }}
  when: features.mysql

- name: 'enable postgresql driver'
  template: src=storage_postgresql.j2 dest={{artifactory_home}}/etc/storage.properties owner=root group=root mode=0644
  when: features.postgresql

- name: 'enable mysql driver'
  template: src=storage_mysql.j2 dest={{artifactory_home}}/etc/storage.properties owner=root group=root mode=0644
  when: features.mysql
